spring:
  application:
    name: mscreditassessor
  rabbitmq:
    host: localhost
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    port: 5672
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
mq:
  queues:
    emissao-cartoes: emissao-cartoes