spring:
  application:
    name: eurekaServer
  security:
    user:
      name: admin
      password: admin4321
server:
  port: 8761 #porta padrao do eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false