spring:
  application:
    name: mscards
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA:http://admin:admin4321@localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
mq:
  queues:
    emissao-cartoes: emissao-cartoes
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/log-file.log